### PR TITLE
Mak 6 refunds and partly refunds straight from the orders page

### PR DESCRIPTION
**Pull request by gambit-mak**
This pull request still has some open issues.

1. Do we have to support in this addon refunds for order payments made with online banking payments? For that customer IBAN is required by Svea API and we don't have the information of the customer IBAN in Woocommerce.

2. How can I make a payment settled in Svea Extranet? Without being able to set payment settled I cannot test the refund after settlement functionality.

3. When is a refund a full refund and when is it a partial refund? Can full refund be detected by comparing refund amount to order amount?

### CODE REVIEW

**Comment by Hene-Svea** [comment]
I will reply to these questions viea email.

**Comment by gambit-mak** [comment]
Thanks for the answers! I did some changes to the pull request based on them. 

I now have implemented the refund after settlement so that the the refund is accepted in the Woocommerce side and a comment is added to the side bar with payment details.
Kuvakaappaus 2020-03-31 16-37-00

Could you translate these texts for me to Finnish so that they are ok for you? I can also do it if you prefer that.
- Make a refund directly in <a href="{extranet_payment_url}">Svea Extranet</a>.
- Made a refund of {amount} € through Svea
- Payment is already settled. A payment to Svea is required to finalize refund.
	<br />Recipient: {recipient}
	<br />IBAN: {iban}
	<br />Reference: {reference}
	<br />Amount: {amount} €'

**Comment by Hene-Svea** [comment]
Here are some proposals for Finnish texts:
- Tee tapahtuman hyvitys Svea Extranetissä
- Hyvitettiin x euroa Svea maksupalvelussa
- Maksu on jo käsitelty. Hyvitysmaksun suorittamiseksi tarvitaan seuraavat tiedot.
Recipient = Maksun saaja
Reference = Viitenumero
Amount = Summa

**Comment by gambit-mak** [comment]
Now the translations are also in the pull request. Now it it is ok to review and test this.

**Comment by Hene-Svea** [comment]
Thanks... I'll begin the testing shortly. Could you update and write something about refund functionality to docs? The current documentation source is in odt format but if you don't have tools to update you may write a separate document. It does not have to be a very detailed documentation. Some hints how to access this functionality and what it does.

**Comment by Hene-Svea** [comment]
I have tested refund cases and extranet linking manually. Very good job!

Would it be possible to add quantity counter or similar UI element to the shipping row also. If you make a partial refund for the product and want to refund shipping also you have to calculate or manually enter the shipping taxes. Automatic calculation for taxes would be nice for the partial product amount refunds too.

But this is very good refund feature implementation overall.

**Comment by Hene-Svea** [comment]
As there is no major problems with this pr I'll merge current changes to master.

**Comment by gambit-mak** [comment]
I will add some documentation tomorrow.

I'll do some research about how the quantity counter idea could work and we will come back to you about that.

**Pull request merged**
