### PR TITLE
MAK-6: Documentation

### PR DESCRIPTION
**Pull request by gambit-mak**
I added section "10.2 Refunds" to documentation .odt and .pdf files.

### CODE REVIEW

**Comment by Hene-Svea** [comment]
Thank you! For the future, do you prefer edit odt first and then publish as a pdf, or edit the pdf file directly?

**Comment by Hene-Svea** [comment]
I'm thinking if we can dismiss this odt format ...

**Comment by gambit-mak** [comment]
In my opinion editing pdf files directly is not very easy. So in here in practice I first edited .odt file and just exported it into a .pdf file. I think we need the .odt file.

**Comment by Hene-Svea** [comment]
That's ok. Let's keep that odt file too.

**Pull request merged**
